return {
	"leif_idol",--树精守卫雕像
	"wagpunkbits_kit",--自动修理机

	"cotl_trinket",--红眼冠
	"wolfgang_whistle",--训练哨

	"wagstaff_mutations_note",--研究笔记
	"scrapbook_page",--丢失的图鉴页面
	-- "scrapbook_page_special",--不见了图鉴页

	"bootleg",--出逃腿靴

	"record",--唱片
	"phonograph",--留声机

	"deerclopseyeball_sentryward_kit",--冰眼结晶器套装
	"voidcloth_kit",--虚空修补套件
	"lunarplant_kit",--亮茄修补套件
	"shadow_forge_kit",--暗影术基座套装
	"lunar_forge_kit",--辉煌铁匠铺套装

	"security_pulse_cage",--火花柜
	"security_pulse_cage_full",--火花柜

	
	"yotr_decor_1_item",--矮兔灯
	"yotr_decor_2_item",--高兔灯
	"yotr_fightring_kit",--枕头大战坑套装
	"yotr_token",--挑战手套

	"playbill_the_doll",--附魔玩偶
	"cookingrecipecard",--酿鱼头食谱
	---------------------------2022-5-20
	"stash_map",--海岛地图
	"blackflag",--黑旗
	"cursed_monkey_token",--诅咒饰品
	--机器人相关物品
	"wx78_scanner_item",
	"scandata",
	"wx78_moduleremover",
	"wx78module_maxhealth",
	"wx78module_maxhealth2",
	"wx78module_heat",
	"wx78module_nightvision",
	"wx78module_music",
	"wx78module_light",
	"wx78module_movespeed",
	"wx78module_movespeed2",
	"wx78module_maxsanity",
	"wx78module_maxsanity1",
	"wx78module_taser",
	"wx78module_cold",
	"wx78module_maxhunger",
	"wx78module_maxhunger1",
	"wx78module_bee",
	---------------------------2022-2-24新增
	"terrarium",
	--
	"moonstorm_static_item",
	"moonglass_charged",
	"alterguardianhatshard",
	"moonstorm_spark",

	--离奇工具
	"wagstaff_tool_1",
	"wagstaff_tool_2",
	"wagstaff_tool_3",
	"wagstaff_tool_4",
	"wagstaff_tool_5",
	-- "wagstaff_npc_pstboss",
	--蜘蛛变身
	"spider_whistle",
	"spider_repellent",
	"mutator_hider",
	"mutator_dropper",
	"mutator_moon",
	"mutator_warrior",
	"spider_healer_item",
	"mutator_spitter",
	"spiderden_bedazzler",
	"mutator_water",
	"mutator_healer",
	--猫
	
	"kitcoon_nametag",
	"cattoy_mouse",
	"kitcoondecor1_kit",
	"kitcoonden_kit",
	"kitcoondecor2_kit",
	--鸭
	"carnivaldecor_figure_kit_season2",--金色神秘盒子
	"carnivaldecor_eggride4_kit",--小型跳楼机套装
	"carnivalgame_puckdrop_kit",--鸟房落球套装
	"carnivalgame_wheelspin_kit",--布谷鸟转盘套装
	"carnivalgame_shooting_kit",--保卫鸟巢套装
	"carnivaldecor_banner_kit",--光线捕捉器套装
	"carnival_gametoken",
	"carnival_prizeticket",
	"carnivalcannon_confetti_kit",
	"carnivaldecor_lamp_kit",
	"carnivalcannon_sparkle_kit",
	"carnivalgame_herding_kit",
	"carnivalcannon_streamer_kit",
	"carnivalgame_feedchicks_kit",
	"carnivalgame_feedchicks_food",
	"carnivalgame_memory_kit",
	"carnivaldecor_eggride3_kit",
	"carnival_plaza_kit",
	"carnivaldecor_eggride2_kit",
	"carnivaldecor_eggride1_kit",
	"carnivaldecor_plant_kit",
	"carnivaldecor_figure_kit",
	"carnival_prizebooth_kit",
	--
	"treegrowthsolution",

	----------------------------
    --战斗道具
    "gunpowder",
    "beemine",
    "trap_teeth",
    "trap_bramble",
    "dug_trap_starfish",
    "sleepbomb",
    "panflute",
    "eyeturret_item",
    --医疗道具
    "healingsalve",
    "bandage",
    "lifeinjector",
    "reviver",
    "compostwrap",
    "tillweedsalve",
    --药水
    "halloweenpotion_bravery_small",
    "halloweenpotion_bravery_large",
    "halloweenpotion_health_small",
    "halloweenpotion_health_large",
    "halloweenpotion_sanity_small",
    "halloweenpotion_sanity_large",
    "halloweenpotion_embers",
    "halloweenpotion_sparks",
    "halloweenpotion_moon",
    --黑暗炼金药剂
    "ghostlyelixir_attack",
    "ghostlyelixir_speed",
    "ghostlyelixir_slowregen",
    "ghostlyelixir_fastregen",
    "ghostlyelixir_shield",
    "ghostlyelixir_retaliation",
    --温泉道具
    "bathbomb",
    --驱赶野兽道具
    "firecrackers",
    --换人道具
    "moonrockidol",
    "moonrockseed",
    "multiplayer_portal_moonrock_constr_plans",
    --换皮肤道具
    "reskin_tool",
    --隐士相关
    "hermit_pearl",
    "hermit_cracked_pearl",
    "messagebottle",
    "messagebottleempty",
    --远古用品
    "archive_lockbox",
    "archive_resonator_item",
    --贝壳钟
    "singingshell_octave3",
    "singingshell_octave4",
    "singingshell_octave5",
    --随从道具
    "abigail_flower",
    "bernie_inactive",
    "lavae_tooth",
    "fruitflyfruit",
    "chester_eyebone",
    "hutch_fishbowl",
    "glommerflower",
    "thurible",
    "houndwhistle",
    "onemanband",
    "pig_coin",
    "beef_bell",
    --暴动检测
    "nightmare_timepiece",
    "atrium_key",
    "shadowheart",
    --人物专属
    "balloons_empty",
    "wortox_soul",
    "battlesong_durability",
    "battlesong_healthgain",
    "battlesong_sanitygain",
    "battlesong_sanityaura",
    "battlesong_fireresistance",
    "battlesong_instant_taunt",
    "battlesong_instant_panic",
	"battlesong_shadowaligned",--黑暗悲歌
	"battlesong_instant_revive",--战士重奏
	"battlesong_lunaraligned",--启迪摇篮曲

    --雕像草图
	"chesspiece_warg_mutated_sketch",--附身座狼雕塑草图
	"chesspiece_deerclops_mutated_sketch",--晶体独眼巨鹿雕塑草图
	"chesspiece_bearger_mutated_sketch",--装甲熊獾雕塑草图
	"chesspiece_daywalker_sketch",--噩梦猪人雕像草图
	"chesspiece_manrabbit_sketch",--兔人雕塑草图
	"chesspiece_kitcoon_sketch",
	"chesspiece_twinsofterror_sketch",
	"chesspiece_guardianphase3_sketch",
	"chesspiece_catcoon_sketch",
	"chesspiece_eyeofterror_sketch",
    "chesspiece_moosegoose_sketch",
    "chesspiece_dragonfly_sketch",
    "chesspiece_bearger_sketch",
    "chesspiece_deerclops_sketch",
    "chesspiece_crabking_sketch",
    "chesspiece_malbatross_sketch",
    "chesspiece_antlion_sketch",
    "chesspiece_beequeen_sketch",
    "chesspiece_klaus_sketch",
    "chesspiece_minotaur_sketch",
    "chesspiece_stalker_sketch",
    "chesspiece_toadstool_sketch",
    "chesspiece_knight_sketch",
    "chesspiece_bishop_sketch",
    "chesspiece_rook_sketch",
    "chesspiece_formal_sketch",
    "chesspiece_muse_sketch",
    "chesspiece_pawn_sketch",
    "chesspiece_anchor_sketch",
    "chesspiece_butterfly_sketch",
    "chesspiece_moon_sketch",
    "chesspiece_claywarg_sketch",
    "chesspiece_clayhound_sketch",
    "chesspiece_carrat_sketch",
    "chesspiece_beefalo_sketch",
    --渔具图纸
    "oceanfishinglure_hermit_drowsy_tacklesketch",
    "oceanfishinglure_hermit_heavy_tacklesketch",
    "oceanfishinglure_hermit_rain_tacklesketch",
    "oceanfishinglure_hermit_snow_tacklesketch",
    "oceanfishingbobber_ball_tacklesketch",
    "oceanfishingbobber_oval_tacklesketch",
    "oceanfishingbobber_crow_tacklesketch",
    "oceanfishingbobber_robin_tacklesketch",
    "oceanfishingbobber_robin_winter_tacklesketch",
    "oceanfishingbobber_canary_tacklesketch",
    "oceanfishingbobber_goose_tacklesketch",
    "oceanfishingbobber_malbatross_tacklesketch",
    --萝卜鼠
    "yotc_carrat_scale_item",
    "yotc_carrat_gym_speed_item",
    "yotc_carrat_gym_reaction_item",
    "yotc_carrat_gym_stamina_item",
    "yotc_carrat_gym_direction_item",
    "yotc_carrat_race_start_item",
    "yotc_carrat_race_checkpoint_item",
    "yotc_carrat_race_finish_item",
    --皮弗娄牛
    "yotb_pattern_fragment_1",
    "yotb_pattern_fragment_2",
    "yotb_pattern_fragment_3",
    "yotb_post_item",
    "yotb_sewingmachine_item",
    "yotb_stage_item",
    "beefalo_groomer_item",
    -----
    ---------------------------------2024-2-24更新
	--感觉蓝图没啥用，就去掉算了
    --随便加的，蓝图，批量导入的，不知道名字
	-- "amulet_blueprint",
	-- "anchor_item_blueprint",
	-- "archive_resonator_item_blueprint",
	-- "armor_sanity_blueprint",
	-- "armordragonfly_blueprint",
	-- "armormarble_blueprint",
	-- "armorslurper_blueprint",
	-- "armorwood_blueprint",
	-- "arrowsign_post_blueprint",
	-- "backpack_blueprint",
	-- "bandage_blueprint",
	-- "batbat_blueprint",
	-- "bearger_fur_blueprint",
	-- "beargervest_blueprint",
	-- "beast_blueprint",
	-- "bedroll_furry_blueprint",
	-- "bedroll_straw_blueprint",
	-- "beebox_blueprint",
	-- "beef_bell_blueprint",
	-- "beefalo_groomer_blueprint",
	-- "beefalohat_blueprint",
	-- "beehat_blueprint",
	-- "beemine_blueprint",
	-- "beeswax_blueprint",
	-- "birdcage_blueprint",
	-- "birdtrap_blueprint",
	-- "blowdart_fire_blueprint",
	-- "blowdart_pipe_blueprint",
	-- "blowdart_sleep_blueprint",
	-- "blowdart_yellow_blueprint",
	-- "blue_mushroomhat_blueprint",
	-- "blueamulet_blueprint",
	-- "boards_blueprint",
	-- "boat_item_blueprint",
	-- "boatpatch_blueprint",
	-- "boomerang_blueprint",
	-- "brush_blueprint",
	-- "bugnet_blueprint",
	-- "bundlewrap_blueprint",
	-- "bushhat_blueprint",
	-- "candybag_blueprint",
	-- "cane_blueprint",
	-- "cartographydesk_blueprint",
	-- "catcoonhat_blueprint",
	-- "chesspiece_anchor_sketch_blueprint",
	-- "coldfire_blueprint",
	-- "coldfirepit_blueprint",
	-- "compostingbin_blueprint",
	-- "cookbook_blueprint",
	-- "cookiecutterhat_blueprint",
	-- "cookpot_blueprint",
	-- "cutstone_blueprint",
	-- "deserthat_blueprint",
	-- "doll_blueprint",
	-- "dragonflychest_blueprint",
	-- "dragonflyfurnace_blueprint",
	-- "dress_blueprint",
	-- "endtable_blueprint",
	-- "eyebrellahat_blueprint",
	-- "farm_blueprint",
	-- "farm_hoe_blueprint",
	-- "farm_plow_item_blueprint",
	-- "featherfan_blueprint",
	-- "featherhat_blueprint",
	-- "featherpencil_blueprint",
	-- "fence_gate_item_blueprint",
	-- "fence_item_blueprint",
	-- "fertilizer_blueprint",
	-- "festive_blueprint",
	-- "firestaff_blueprint",
	-- "firesuppressor_blueprint",
	-- "fish_box_blueprint",
	-- "fishingrod_blueprint",
	-- "footballhat_blueprint",
	-- "formal_blueprint",
	-- "giftwrap_blueprint",
	-- "goggleshat_blueprint",
	-- "golden_farm_hoe_blueprint",
	-- "goldenaxe_blueprint",
	-- "goldenpickaxe_blueprint",
	-- "goldenshovel_blueprint",
	-- "green_mushroomhat_blueprint",
	-- "gunpowder_blueprint",
	-- "hambat_blueprint",
	-- "hawaiianshirt_blueprint",
	-- "healingsalve_blueprint",
	-- "heatrock_blueprint",
	-- "homesign_blueprint",
	-- "ice_blueprint",
	-- "icebox_blueprint",
	-- "icehat_blueprint",
	-- "icepack_blueprint",
	-- "icestaff_blueprint",
	-- "lantern_blueprint",
	-- "lifeinjector_blueprint",
	-- "light_blueprint",
	-- "lightning_rod_blueprint",
	-- "madscience_lab_blueprint",
	-- "magic_blueprint",
	-- "malbatross_feathered_weave_blueprint",
	-- "marblebean_blueprint",
	-- "mast_item_blueprint",
	-- "mast_malbatross_item_blueprint",
	-- "mastupgrade_lamp_item_blueprint",
	-- "mastupgrade_lightningrod_item_blueprint",
	-- "meatrack_blueprint",
	-- "minerhat_blueprint",
	-- "minisign_blueprint",
	-- "minisign_item_blueprint",
	-- "molehat_blueprint",
	-- "moon_device_construction1_blueprint",
	-- "moondial_blueprint",
	-- "moonrockcrater_blueprint",
	-- "moonstorm_goggleshat_blueprint",
	-- "mushroom_farm_blueprint",
	-- "mushroom_light2_blueprint",
	-- "mushroom_light_blueprint",
	-- "nature_blueprint",
	-- "nightlight_blueprint",
	-- "nightmarefuel_blueprint",
	-- "nightstick_blueprint",
	-- "nightsword_blueprint",
	-- "oar_blueprint",
	-- "oar_driftwood_blueprint",
	-- "oceanfishingrod_blueprint",
	-- "onemanband_blueprint",
	-- "panflute_blueprint",
	-- "papyrus_blueprint",
	-- "perdshrine_blueprint",
	-- "piggyback_blueprint",
	-- "pighouse_blueprint",
	-- "pigshrine_blueprint",
	-- "pitchfork_blueprint",
	-- "plantregistryhat_blueprint",
	-- "pocket_scale_blueprint",
	-- "pottedfern_blueprint",
	-- "premiumwateringcan_blueprint",
	-- "pumpkin_lantern_blueprint",
	-- "purpleamulet_blueprint",
	-- "purplegem_blueprint",
	-- "rabbithouse_blueprint",
	-- "raincoat_blueprint",
	-- "rainhat_blueprint",
	-- "rainometer_blueprint",
	-- "razor_blueprint",
	-- "red_mushroomhat_blueprint",
	-- "refine_blueprint",
	-- "refined_dust_blueprint",
	-- "reflectivevest_blueprint",
	-- "researchlab2_blueprint",
	-- "researchlab3_blueprint",
	-- "researchlab4_blueprint",
	-- "reskin_tool_blueprint",
	-- "resurrectionstatue_blueprint",
	-- "robot_blueprint",
	-- "rope_blueprint",
	-- "ruinsrelic_bowl_blueprint",
	-- "ruinsrelic_chair_blueprint",
	-- "ruinsrelic_chipbowl_blueprint",
	-- "ruinsrelic_plate_blueprint",
	-- "ruinsrelic_table_blueprint",
	-- "ruinsrelic_vase_blueprint",
	-- "saddle_basic_blueprint",
	-- "saddle_race_blueprint",
	-- "saddle_war_blueprint",
	-- "saddlehorn_blueprint",
	-- "saltbox_blueprint",
	-- "saltlick_blueprint",
	-- "scarecrow_blueprint",
	-- "science_blueprint",
	-- "sculptingtable_blueprint",
	-- "seafaring_blueprint",
	-- "seafaring_prototyper_blueprint",
	-- "seedpouch_blueprint",
	-- "sentryward_blueprint",
	-- "sewing_kit_blueprint",
	-- "shovel_blueprint",
	-- "siestahut_blueprint",
	-- "sleepbomb_blueprint",
	-- "soil_amender_blueprint",
	-- "spear_blueprint",
	-- "staff_tornado_blueprint",
	-- "steeringwheel_item_blueprint",
	-- "succulent_potted_blueprint",
	-- "survival_blueprint",
	-- "sweatervest_blueprint",
	-- "table_winters_feast_blueprint",
	-- "tacklestation_blueprint",
	-- "telebase_blueprint",
	-- "telestaff_blueprint",
	-- "tent_blueprint",
	-- "tillweedsalve_blueprint",
	-- "tools_blueprint",
	-- "tophat_blueprint",
	-- "town_blueprint",
	-- "townportal_blueprint",
	-- "transistor_blueprint",
	-- "trap_teeth_blueprint",
	-- "treasurechest_blueprint",
	-- "treegrowthsolution_blueprint",
	-- "trident_blueprint",
	-- "trophyscale_fish_blueprint",
	-- "trophyscale_oversizedveggies_blueprint",
	-- "trunkvest_summer_blueprint",
	-- "trunkvest_winter_blueprint",
	-- "turf_carpetfloor_blueprint",
	-- "turf_checkerfloor_blueprint",
	-- "turf_dragonfly_blueprint",
	-- "turf_road_blueprint",
	-- "turf_shellbeach_blueprint",
	-- "turf_woodfloor_blueprint",
	-- "turfcraftingstation_blueprint",
	-- "umbrella_blueprint",
	-- "victorian_blueprint",
	-- "wall_hay_item_blueprint",
	-- "wall_moonrock_item_blueprint",
	-- "wall_stone_item_blueprint",
	-- "wall_wood_item_blueprint",
	-- "war_blueprint",
	-- "wardrobe_blueprint",
	-- "wargshrine_blueprint",
	-- "wartab_blueprint",
	-- "waterballoon_blueprint",
	-- "wateringcan_blueprint",
	-- "watermelonhat_blueprint",
	-- "waterpump_blueprint",
	-- "waxpaper_blueprint",
	-- "whip_blueprint",
	-- "winch_blueprint",
	-- "winter_treestand_blueprint",
	-- "winterhat_blueprint",
	-- "winterometer_blueprint",
	-- "wintersfeastoven_blueprint",
	-- "yot_catcoonshrine_blueprint",
	-- "yotb_beefaloshrine_blueprint",
	-- "yotc_carratshrine_blueprint"
}
