return {
    --指示牌
    "minisign_drawn",
    "minisign_item",
    --围栏
    "fence_item",
    "fence_gate_item",
    --墙体
    "wall_dreadstone_item",--绝望石墙
    "wall_hay_item",
    "wall_wood_item",
    "wall_stone_item",
    "wall_ruins_item",
    "wall_moonrock_item",
    --自然地皮

    "turf_beard_rug",--胡须地毯
    "turf_ruinsbrick",--远古地面
    "turf_ruinstiles",--远古瓷砖
    "turf_ruinstrim",--远古砖雕
    "turf_monkey_ground",--月亮码头海滩地皮
    "turf_deciduous",
    "turf_forest",
    "turf_grass",
    "turf_marsh",
    "turf_rocky",
    "turf_desertdirt",
    "turf_savanna",
    "turf_underrock",
    "turf_fungus",
    "turf_fungus_green",
    "turf_fungus_red",
    "turf_cave",
    "turf_mud",
    "turf_sinkhole",
    "turf_pebblebeach",
    "turf_meteor",
    "turf_shellbeach",
    "turf_fungus_moon",
    "turf_archive",
    --人造地皮
    "turf_cotl_brick",--砖地板
    "turf_cotl_gold",--黄金地板
    "turf_carpetfloor2",--茂盛地毯
    "turf_mosaic_red",--红色马赛克地面
    "turf_mosaic_blue",--蓝色马赛克地面
    "turf_mosaic_grey",--灰色马赛克地面
    "turf_ruinsbrick_glow",--仿远古地面
    "turf_ruinstiles_glow",--仿远古瓷砖
    "turf_ruinstrim_glow",--仿远古砖雕
    "dock_kit",--码头套装
    "turf_road",
    "turf_woodfloor",
    "turf_checkerfloor",
    "turf_carpetfloor",
    "turf_dragonfly",


}
