return {
	"charlie_hand",--召唤之手
	"wagstaff_machinery",--被丢弃的垃圾
	"carpentry_station",--锯马

	"support_pillar_scaffold",--支柱脚手架
	"support_pillar",--支柱瓦砾
	"support_pillar_dreadstone_scaffold",--绝望石支柱脚手架
	"support_pillar_dreadstone",--绝望石支柱瓦砾

	"deerclopseyeball_sentryward",--冰眼结晶器



	"yotr_rabbitshrine",--兔人神龛
	"yotr_fightring_bell",--枕头大战钟
	"yotr_fightring",--枕头大战坑
	"yotr_fightring_torch",--兔人火炬
	"yotr_decor_1",--矮兔灯
	"yotr_decor_2",--高兔灯

	
	"punchingbag",--拳击袋
	"punchingbag_shadow",--暗影拳击袋
	"punchingbag_lunar",--明亮拳击袋
	"sewing_mannequin",--假人

	"bookstation",--书架
	--航海
	"boat_cannon",--大炮
	"pirate_flag_pole",--月亮码头海盗旗
	"boat_pirate",--海盗单桅帆船
	"boat_rotator",--转向舵
	"boat_magnet",--自动航行
	"boat_bumper_shell",--贝壳保险杠
	"boat_bumper_kelp",--海带保险杠
	"ocean_trawler",--海洋拖网捕鱼器
	"boat_grass",--草筏
	"walkingplank_grass",--木板
	"boat",
	"steeringwheel",
	"anchor",
	"mast",
	"mast_malbatross",
	"winch",
	"waterpump",
	
--机器人
	"wx78_scanner_succeeded",
--泰拉
	"terrariumchest",
--月亮实验
	"moon_device_construction1",
--墙体

	"wall_dreadstone",--绝望石墙
	"brokenwall_dreadstone",--铥墙
	"wall_hay",
	"brokenwall_hay",
	"wall_wood",
	"brokenwall_wood",
	"wall_stone",
	"brokenwall_stone",
	"wall_ruins",
	"brokenwall_ruins",
	"wall_moonrock",
	"brokenwall_moonrock",
--围栏
	"fence",
	"fence_gate",
--放牧
	"saltlick",
--火堆
	"cotl_tabernacle_level1",--低微咩咩雕像
	"cotl_tabernacle_level2",--有所改进咩咩雕像
	"cotl_tabernacle_level3",--完美无瑕咩咩雕像
	"campfire",
	"firepit",
	"coldfire",
	"coldfirepit",
	"nightlight",
--照明
	"mushroom_light",
	"mushroom_light2",
--过夜
	"tent",
	"siestahut",
	"portabletent",
--农场
	"slow_farmplot",
	"fast_farmplot",
	"mushroom_farm",
--农具
	"farm_plow",
	"trophyscale_oversizedveggies",
	"compostingbin",
--蜂箱
	"beebox",
--晒肉
	"meatrack",
--烹饪
	"cookpot",
	"portablecookpot",
	"portableblender",
	"portablespicer",
--保鲜
	"icebox",
	"saltbox",
	"fish_box",
	"trophyscale_fish",
--冬季盛宴
	"table_winters_feast",
	"wintersfeastoven",
--气象
	"winterometer",
	"rainometer",
	"lightning_rod",
--灭火
	"firesuppressor",
--标记
	"minisign",
	"homesign",
	"arrowsign_post",
--储存
	"treasurechest",
	"dragonflychest",
--取暖
	"dragonflyfurnace",
--换装
	"wardrobe",
--稻草人
	"scarecrow",
--鸟笼
	"birdcage",
--复活
	"resurrectionstatue",
--魔法
	"telebase",
	"sentryward",
	"moondial",
	"townportal",
	"eyeturret",
--薇诺娜
	"winona_battery_high",
	"winona_battery_low",
	"winona_catapult",
	"winona_spotlight",
--温蒂
	"sisturn",
--科技
	"shadow_forge",--暗影术基座
	"lunar_forge",--辉煌铁匠铺
	"researchlab",
	"researchlab2",
	"cartographydesk",
	"sculptingtable",
	"madscience_lab",
	"seafaring_prototyper",
	"tacklestation",
	"researchlab4",
	"researchlab3",
	--大力士
	"mighty_gym",
--祭坛
	"archive_switch",
	"ancient_altar_broken",
	"ancient_altar",
	"turfcraftingstation",
	"moon_altar",
	"moon_altar_cosmic",
	"moon_altar_astral",
	"moon_altar_icon", 
	"moon_altar_ward",
	"archive_resonator",
	"perdshrine",
	"wargshrine",
	"pigshrine",
	"yotc_carratshrine",
	"yotb_beefaloshrine",
	--猫
	"yot_catcoonshrine",
	"kitcoondecor2",
	"kitcoonden",

	--鸭
	"carnivaldecor_banner",--光线捕捉器
	"carnivalgame_shooting_station",--保卫鸟巢
	"carnivalgame_puckdrop_station",--鸟房落球
	"carnivalgame_wheelspin_station",--布谷鸟转盘
	"carnivaldecor_eggride4",--小型跳楼机
	"carnivaldecor_figure_season2",--普通鸦年华小雕像
	"carnivalgame_shooting_button",--保卫鸟巢
	"carnivalgame_shooting_target",--活板门
	"carnivalgame_feedchicks_station",
	"carnivalgame_memory_station",	
	"carnivalgame_herding_station",
	"carnivaldecor_figure",
	"carnivaldecor_lamp",
	"carnivalcannon_streamer",
	"carnivaldecor_eggride1",
	"carnivaldecor_eggride2",
	"carnivaldecor_eggride3",
	"carnivaldecor_plant",
	"carnival_plaza",
	"carnivalcannon_confetti",
	"carnivalgame_herding_chick",
	"carnivalcannon_sparkle",
	"carnival_prizebooth",
	
	--火鸡
	"kitcoondecor1",
	--萝卜鼠
	"yotc_carrat_scale",
	"yotc_carrat_gym_speed",
	"yotc_carrat_gym_reaction",
	"yotc_carrat_gym_stamina",
	"yotc_carrat_gym_direction",
	"yotc_carrat_race_start",
	"yotc_carrat_race_checkpoint",
	"yotc_carrat_race_finish",
--皮弗娄牛
	"yotb_post",
	"yotb_sewingmachine",
	"yotb_stage",
	"beefalo_groomer",
--装饰
	"wood_table_square",--木方桌
	"wood_stool",--木凳
	"wood_chair",--木椅
	"wood_table_round",--木圆桌
	"winter_palmconetree",--冬季盛宴树
	"endtable",
	"succulent_potted",
	"pottedfern",
	"winter_treestand",
--古代家具
	"ruinsrelic_plate",
	"ruinsrelic_chipbowl",
	"ruinsrelic_bowl",
	"ruinsrelic_vase",
	"ruinsrelic_chair",
	"ruinsrelic_table",
--隐士小岛
	"beebox_hermit",
	"meatrack_hermit",

	
}