return {
	
	"staff_lunarplant",--亮茄魔杖
	"sword_lunarplant",--亮茄剑
	"bomb_lunarplant",--亮茄炸弹
	

	"cannonball_rock_item",--炮弹
	--武器
	"voidcloth_scythe",--暗影收割者
	"houndstooth_blowpipe",--嚎弹炮
	"spear_wathgrithr_lightning",--奔雷矛
	"spear_wathgrithr_lightning_charged",--充能奔雷矛
	"fence_rotator",--栅栏击剑
	"oar_monkey",--战桨
	"cutless",--木头短剑
	"pocketwatch_weapon",
	"walking_stick",--木手杖
	"cane",
	"bullkelp_root",
	"whip",
	"spear",
	"spear_wathgrithr",
	"batbat",
	"trident",
	"tentaclespike",
	"hambat",
	"ruins_bat",
	"nightsword",
	"glasscutter",
	"nightstick",



	"boomerang",
	"blowdart_pipe",
	"blowdart_yellow",
	"blowdart_sleep",
	"blowdart_fire",
	"staff_tornado",
	--气球
	"balloonparty",
	"balloon",
	"balloonspeed",
	--盾牌
	"shieldofterror",
	"wathgrithr_shield",--战斗圆盾
	--投掷武器
	"dumbbell_heat",--热铃
	"dumbbell_bluegem",--冰铃
	"dumbbell_redgem",--火铃
	"dumbbell_gem",
	"dumbbell_golden",
	"dumbbell_marble",
	"dumbbell",

	"waterplant_bomb",

	--弹弓
	"slingshot",
	--弹药
	"slingshotammo_rock",
	"slingshotammo_gold",
	"slingshotammo_marble",
	"slingshotammo_poop",
	"slingshotammo_freeze",
	"slingshotammo_slow",
	"slingshotammo_thulecite",
	--头盔
	"voidclothhat",--虚空风帽
	"wagpunkhat",--W.A.R.B.I.S.头戴齿轮
	"woodcarvedhat",--硬木帽
	"wathgrithr_improvedhat",--统帅头盔
	"lunarplanthat",--亮茄头盔
	"dreadstonehat",--绝望石头盔
	"cookiecutterhat",
	"alterguardianhat",
	"footballhat",
	"wathgrithrhat",
	"beehat",
	"ruinshat",
	"slurtlehat",
	"hivehat",
	"skeletonhat",
	"balloonhat",
	"eyemaskhat",
	--护甲
	"armorwagpunk",--W.A.R.B.I.S.盔甲
	"armor_voidcloth",--虚空长袍
	"armor_lunarplant",--亮茄盔甲
	"armordreadstone",--绝望石盔甲
	"armorgrass",
	"armor_bramble",
	"armorwood",
	"armorruins",
	"armor_sanity",
	"armormarble",
	"armorsnurtleshell",
	"armordragonfly",
	"armorskeleton",
	"balloonvest",
	--背包
	"backpack",
	"piggyback",
	"krampus_sack",
	"spicepack",
	"icepack",
	"candybag",
	"seedpouch",
}
