return {
	"lunarthrall_plant",--致命亮茄
	"daywalker",--噩梦猪人
	--猪王
	"monkeyqueen",--月亮码头女王
	"pigking",
--月亮boss
	"alterguardian_phase1",
	"alterguardian_phase2",
	"alterguardian_phase3",
	"twinofterror1",
	"twinofterror2",
	"eyeofterror",
--四季boss
	"moose",
	"antlion",
	"bearger",
	"deerclops",
--领地boss
	"dragonfly",
	"malbatross",
	"beequeen",
	"klaus",
	"crabking",
	"toadstool",
	"toadstool_dark",
	"minotaur",
--骨架
	"stalker",
	"stalker_forest",
	"stalker_atrium",
--暗影boss
	"shadow_knight",
	"shadow_rook",
	"shadow_bishop",
--树精
	"leif",
	"leif_sparse",
	"deciduoustree",
--怪物首领
	"lordfruitfly",
	"spiderqueen",
	"warg",
	"warglet",
	"claywarg",
	"gingerbreadwarg",
	"spat",
}