return {
	"nightcaphat",--睡帽
	
	"handpillow_beefalowool",--皮弗娄牛毛枕头
	"handpillow_petals",--花朵枕头
	"handpillow_kelp",--海带枕头
	"handpillow_steelwool",--钢丝绵枕头

	"bodypillow_kelp",--海带枕头盔甲
	"bodypillow_petals",--花朵枕头盔甲
	"bodypillow_steelwool",--钢丝绵枕头盔甲
	"bodypillow_beefalowool",--皮弗娄牛枕头盔甲

	"antlionhat",--刮地皮头盔

	"mask_queenhat",--女王面具
	"costume_queen_body",--女王服
	"mask_dollbrokenhat",--开裂玩偶面具
	"mask_dollrepairedhat",--破碎玩偶面具
	"mask_dollhat",--玩偶面具
	"costume_doll_body",--玩偶服
	"mask_treehat",--树木面具
	"costume_tree_body",--树木服
	"mask_blacksmithhat",--铁匠面具
	"costume_blacksmith_body",--铁匠服
	"mask_foolhat",--小丑面具
	"costume_fool_body",--小丑服
	"mask_mirrorhat",--镜子面具
	"costume_mirror_body",--镜子服
	"mask_kinghat",--国王面具
	"costume_king_body",--国王服


	"polly_rogershat",--波莉·罗杰的帽子
	"monkey_smallhat",--海盗头巾
	"monkey_mediumhat",--船长的三角帽

	"carnival_vest_c",
	"carnival_vest_a",
	"carnival_vest_b",
	--花环
	"kelphat",
	"flowerhat",
	--精神
	"featherhat",
	"tophat",
	"walterhat",
	--风镜
	"moonstorm_goggleshat",
	"goggleshat",
	"deserthat",
	--保暖
	"catcoonhat",
	"earmuffshat",
	"winterhat",
	"walrushat",
	"beefalohat",
	--避雨降温
	"red_mushroomhat",
	"blue_mushroomhat",
	"green_mushroomhat",
	"strawhat",
	"watermelonhat",
	"icehat",
	"rainhat",
	"eyebrellahat",
	--新年装扮
	"dragonheadhat",
	"dragonbodyhat",		
	"dragontailhat",
	--其他帽子
	"mermhat",
	"bushhat",
	"spiderhat",
	--特殊
	"batnosehat",
	"plantregistryhat",
	"nutrientsgoggleshat",
	--避雨保暖
	"voidcloth_umbrella",--暗影伞
	"trunkvest_summer",
	"raincoat",
	--保暖
	"sweatervest",
	"trunkvest_winter",
	"beargervest",
	--降温
	"reflectivevest",
	"hawaiianshirt",
	--延缓饥饿
	"armorslurper",
}
