return {
	"cannonball_rock_item",--炮弹
	--武器
	"fence_rotator",--栅栏击剑
	"oar_monkey",--战桨
	"cutless",--木头短剑
	"pocketwatch_weapon",
	"cane",
	"bullkelp_root",
	"whip",
	"spear",
	"spear_wathgrithr",
	"batbat",
	"trident",
	"tentaclespike",
	"hambat",
	"ruins_bat",
	"nightsword",
	"glasscutter",
	"nightstick",



	"boomerang",
	"blowdart_pipe",
	"blowdart_yellow",
	"blowdart_sleep",
	"blowdart_fire",
	"staff_tornado",
	"balloonspeed",
	"shieldofterror",
	--投掷武器

	"waterplant_bomb",
	"dumbbell_gem",
	"dumbbell_golden",
	"dumbbell_marble",
	"dumbbell",

	--弹弓
	"slingshot",
	--弹药
	"slingshotammo_rock",
	"slingshotammo_gold",
	"slingshotammo_marble",
	"slingshotammo_poop",
	"slingshotammo_freeze",
	"slingshotammo_slow",
	"slingshotammo_thulecite",
	--头盔
	
	"cookiecutterhat",
	"alterguardianhat",
	"footballhat",
	"wathgrithrhat",
	"beehat",
	"ruinshat",
	"slurtlehat",
	"hivehat",
	"skeletonhat",
	"balloonhat",
	"eyemaskhat",
	--护甲
	"armorgrass",
	"armor_bramble",
	"armorwood",
	"armorruins",
	"armor_sanity",
	"armormarble",
	"armorsnurtleshell",
	"armordragonfly",
	"armorskeleton",
	"balloonvest",
	--背包
	"backpack",
	"piggyback",
	"krampus_sack",
	"spicepack",
	"icepack",
	"candybag",
	"seedpouch",
}
